// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdsyqsrxjffogesoceev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhkc3lxc3J4amZmb2dlc29jZWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDIxNzEsImV4cCI6MjA1NzI3ODE3MX0.BvPVOYcyN0z--In4VsfrjtfiEbI8Ov-GliMOo-xn3Qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);